name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -yq build-essential 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl
      - run: cargo install cross
      - name: Build Rust service
        run: cross build --target x86_64-unknown-linux-musl --release -Z unstable-options
      - name: Build frontend
        working-directory: www
        run: |
          npm i
          npm run build
      - name: Gather artifacts
        run: |
          mkdir target/dist
          cp target/x86_64-unknown-linux-musl/release/srcom-book target/dist
          cp -a www/public target/dist
      - uses: actions/upload-artifact@v2
        with:
          name: srcom-book
          path: target/dist
